### ISSUE TITLE
Master branch HW vs Emu jet rates analyser crashes

### ISSUE THREAD

**Issue by professor-calculus** [cms-l1t-offline/cms-l1t-analysis#115]
#### Description
Using the new master branch I cannot get the HW vs Emu rates analyser to work. I have a PR open #114 which adds some overlaid HW vs Emu plots, but this is made on top of an older version of the code.

I have updated this to match the style etc of the newer version, but since the analyser does not work I cannot test it...

The error I get is: TypeError: branch `L1Upgrade` has unsupported type `L1Analysis::L1AnalysisL1UpgradeDataFormat`

#### Steps/code to reproduce issue
Just try to run 'cmsl1t -c config/HW_Emu_jet_rates.yaml -n 1000'

**Comment by kreczko** [comment]
Did you run `make build` before running this? If yes, do you see `build/L1TAnalsysisDataformats.so`?
Also, Aaron has made quite a lot of changes since, maybe things are working with latest version?

**Comment by kreczko** [comment]
@professor-calculus Are you still experiencing this problem?

**Comment by professor-calculus** [comment]
Hi, looks like the functionality was added in #136 but is pretty much the same. I can get the (same) analyser called up by rates.yaml to work on Aaron’s repository fine now so I suspect it was just the coding style change at the time, I think his version was ahead by quite a bit.

BTW interestingly though the same rates.yaml analyser does not work on the latest v0.5.0 of the main repo, it cites “ ‘Event’ object has no attribute ‘_run’ “ and seg faults...

In any case we can close this issue, as what I’m seeing now is a new one!

Cheers

**Comment by kreczko** [comment]
Yes, in 0.5.0 you need to use `event['run']`. I've moved all existing analyzers to that syntax, but obviously not anything unmerged
