### ISSUE TITLE
Suggestion for plotting and histogram collections

### ISSUE THREAD

**Issue by benkrikler** [cms-l1t-offline/cms-l1t-analysis#14]
I would like to suggest some changes to the way the histogram collections are managed.
The current implementation creates a collection class for each type of histogram.
It also puts it's first 'key' dimension as the pile-up bin. And in the case of the 'efficiency' histograms, the second 'key' dimension is the variable being studied (eg. a different MET sum, total ET in all towers, etc).

I would like to suggest that we:
1. Define a generic 'histogram collection' class, which works generally for all histogram types that we create (so the same collection class can receive efficiency histograms, rate curves, etc).
2. Make the 'key' system assign no special meaning to any key in particular. In the present system that means that 'pile-up' could be the first of the keys but it could be the second, third, and so on.

I've been trying to implement things with the current set up, but have been finding it tricky with the current 'key' structure. In particular, putting the second key dimension as the 'variable' being studied feels awkward.  I would prefer it to be first, but this would become trivial if we adopt option 2 above.  

With (2) in place, I think it could make code easier to read if we allow time access with tuples, like numpy does, eg: `histograms[key1,key2,key3]` as opposed to `histograms[key1][key2][key3]`.

Item (1) will reduce the effort to add a new type of histogram and standardise somewhat the way we work with them.  It may require we add some type of base histogram class (at the moment, as far as I can see, there is only a base for histogram-collections), which would ensure common methods for a histogram are implemented (for example, `fill`, `plot`, `to_root`, `merge`, etc). 

What do people think? @kreczko 

Related issues: #3, #4

**Comment by benkrikler** [comment]
To expand on my issue with putting the 'variable' name second, in the efficiency collection at least, I'm now trying to implement the plotting of efficiency curves.  For each variable I want to plot on one canvas:
 - The turn-on for different pile-up bins at a fixed threshold
 - The turn-on for different thresholds integrated over all pile-up bins
 - The turn-on for different pile-up bins for the different thresholds
This is possible in the current implementation, but it's pretty awkward.

In addition, since can potentially generate a lot of histograms in the process, and these all get saved to a root file, it would be nice to give some internal TDirectory structure to the root file, so that it's a bit easier to digest when we Browse or Ls the contents.  It would seem more natural then to put the variable name first, but again this is a bit awkward in the current approach.

**Comment by kreczko** [comment]
Yes, this is pretty much what I had in mind.

> Define a generic 'histogram collection' class, which works generally for all histogram types that we create (so the same collection class can receive efficiency histograms, rate curves, etc).

That's already the case with `BaseHistCollection` :).

> Make the 'key' system assign no special meaning to any key in particular. In the present system that means that 'pile-up' could be the first of the keys but it could be the second, third, and so on.

Again, that's `BaseHistCollection` in a nutshell.

> I've been trying to implement things with the current set up, but have been finding it tricky with the current 'key' structure. In particular, putting the second key dimension as the 'variable' being studied feels awkward. I would prefer it to be first, but this would become trivial if we adopt option 2 above.

So we would need to re-arrange the specialisations. The reason it is currently done the other way around is caching for the access in the for loops in the fill method. If we go the more bare-bone approach, this can be changed.


> With (2) in place, I think it could make code easier to read if we allow time access with tuples, like numpy does, eg: histograms[key1,key2,key3] as opposed to histograms[key1][key2][key3]

Numpy and Pandas have two different implementations here
```python
result[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M],..., ind_N[i_1, ..., i_M]]
```
and
```python
>>> x = np.array([[1, 2], [3, 4], [5, 6]])
>>> x[[0, 1, 2], [0, 1, 0]]
array([1, 4, 5])
```
If you want to keep things in sync, the equivalent for `histograms[key1][key2][key3]` would be `histograms[[key1,key2,key3]]`, wouldn't it?

All in all, most of the functionality should end up in `BaseHistCollection`.
We could move the binned accessors from specialisations of `BaseHistCollection` to the base class and add `bins=None` to the constructor. One could then implement binning by passing a tuple with entries for each dimension, e.g.
```python
# for dim1=histogram name, dim2=pileup, dim3=threshold
myColl = BaseHistCollection(dimensions=3, bins=(0, (0, 10, 20, 30, 999), (30, 50, 100, 200)))
```

**Comment by benkrikler** [comment]
> > Define a generic 'histogram collection' class, which works generally for all histogram types that we create (so the same collection class can receive efficiency histograms, rate curves, etc).
> 
> That's already the case with `BaseHistCollection` :).
> 
> > Make the 'key' system assign no special meaning to any key in particular. In the present system that means that 'pile-up' could be the first of the keys but it could be the second, third, and so on.
> 
> Again, that's `BaseHistCollection` in a nutshell.

Sort of. What I had in mind was a single `HistCollection` class, that doesn't need to be sub-classed to be usable. Right now, every histogram type has to derive from BaseHistCollection and sticks a load of extra methods on top of it.  The actual BaseHistCollection is pretty sparse.  What you suggest at the end of your message sounds about right to me.

We'd need to give some thought for how this all gets handled for turning the histograms into plots.  How would we then, for example, overlay all pile-up binned histograms for a fixed threshold, and all threshold histograms integrating over pile-up bins?  My initial idea would be for each 'plotter' to be given an appropriate HistCollection object which it would be able to select and overlay appropriate combinations of histograms.

> If you want to keep things in sync, the equivalent for `histograms[key1][key2][key3]` would be `histograms[[key1,key2,key3]]`, wouldn't it?

You've taken that further than I meant!  I was not thinking of obtaining lists of histograms (although perhaps there are uses for doing this).  I just meant accessing a single one.
In your numpy example, then, the only situation I meant to reproduce would be more like:
```python
>>> x = np.array([[1, 2], [3, 4], [5, 6]])
>>> x[0,1]
array([2]) # Although in our case, we'd want the value of the single element rather than an array
```
I can imagine doing something like:
```
>>> summarize(x[:,0])
```
could potentially be used, but this is way more than I was suggesting before, and I think it would definitely be something for the long-term if we agreed it wanted.

**Comment by kreczko** [comment]
Since we are at it, we should also work on reducing the API for the histogram collections. 
The more legacy scripts I process the more clear it becomes.

**Comment by kreczko** [comment]
I am slowly starting to get an overview what is needed for the histogram collections and thus thinking of generalisations. As I see it the current requirements are:
 - support for 1D, 2D (and 3D?) histograms
 - support for smart binning in >=1 dimension: pileup, regions (B, BE, E, HF)
 - support for summaries
 - folder structure for the pickling process  (extension of [rootpy.io.pickler](https://github.com/rootpy/rootpy/blob/master/rootpy/io/pickler.py)?)
 - no subclasses


Generalisation for 1-3 D histograms should be easy by reimplementing `add` :
```python
coll.add('1Dhistogram', bins=[1,2,3])
coll.add('2Dhistogram', bins=[[1,2,3], [1,2,3]])
coll.add('3Dhistogram', bins=[[1,2,3], [1,2,3], [1,2,3]])
```
and fill
```python
coll.fill('1Dhistogram', x=42, w=1)
coll.fill('2Dhistogram', x=[42, 1], w=1) 
#etc
```

In order to make `histograms[key1,key2,key3]` and `histograms[key1][key2][key3]` work in a similar fashion the actual histograms would need to be stored in a proxy object - a wrapper.
```python
proxy.fill( x=[42, 1], w=1)
# would call
histogram.fill(42, 1, 1)
```

Last but not least we would need a way to easily create binning for each dimension.
This could work with something like (names to be changed)
```python
def getter_pileup(value, binning)
        if pileup > max(binning):
            return -1
        bins = pairwise(binning)
        for i, (lowerEdge, upperEdge) in enumerate(bins):
            if pileup >= lowerEdge and pileup < upperEdge:
                return i
        return 0

def getter_region(eta, regions):
    for region in regions:
        if is_in_region(region, eta, regions=regions):
            return region

coll.register_dim(1, getter_pileup, [0, 10, 20, 30, 999])
coll.register_dim(2, getter_region, ['B', 'BE', 'E', 'HF'])

# in the event loop one would then
coll.set_dim(1, pileup)
coll.set_dim(2, region)
# fill hists
# or
coll[pileup][eta][histname].fill(...)
```
