### ISSUE TITLE
rootpy's TreeChain doesn't work with globbing and xrootd access

### ISSUE THREAD

**Issue by benkrikler** [cms-l1t-offline/cms-l1t-analysis#16]
Using TreeChain instead of TChain directly is more pythonic and has nicer logging.
However, TChain's `Add` method can be given globbed file names, which can take globbed names (wild-cards) and expands them.  This works for local files and for files on xrootd.  rootpy's TreeChain, however, wants the list of files expanded in advance. For local files, python's glob package is sufficient.  For files on xrootd however, I dont know of a way to do this just now, which means we'd have to first run `eos ls` to get the file list and then stick that into the config file.

I'll see if I can work out how to reproduce 'globbing' with XRootD files based on how TChain::Add works.

**Comment by benkrikler** [comment]
It looks like TChain just wraps up a series of checks to first:
 - Look for wild-carding in the supplied filename 
 - If found, splits the filename into a directory and basename (which will include the wild-card)
 - Uses `TSystem` to open the directory.  TSystem itself wraps up the calls needed to query xrootd.
 - Switched any wild-carding to a regular expression and checks all filenames in the directory against this regex and adds those that do into the TChain.

I think the best bet is to turn this behaviour into an extended `glob` function.  I'll write this as a util here, then put it into a PR for rootpy I think.  Might be worth opening an issue there too, see if anyone else has found this.

**Comment by benkrikler** [comment]
@kreczko, I'm tempted to put this under the next release milestone (Alpha 0.1.2, right?), since it would be a real pain to have to specify all files by hand.

**Comment by kreczko** [comment]
You type faster than I can collect information ;).

@benkrikler Yes, I agree, improvement should go into [rootpy](https://github.com/rootpy/rootpy).

https://github.com/xrootd/xrootd-python package exists, but looks abandoned and with little documentation.

BTW: Next release is 0.1.1, but I think we will crank out release quite fast to start with :)

**Comment by benkrikler** [comment]
Merge request #18 provides a working (but potentially temporary) solution to this issue, so I'm closing this off.

**Comment by benkrikler** [comment]
Just to update this, my PR for rootpy (https://github.com/rootpy/rootpy/pull/743) was accepted about 2 weeks back, which (added an improved version of) the extended glob functionality I implemented in #18.
