### ISSUE TITLE
Improvements to base histogram collection

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#4]
There are still two non-urgent issues to be solved for the [BaseHistCollection](https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/cmsl1t/collections/base.py)
    - [] add iterator
    - [] Need to be able to specify lambda expression per dimension: This will allow us to have custom dicts or objects in certain dimensions

**Comment by benkrikler** [comment]
As of #37 and #38 this issue is no longer really relevant, so I'm going to close it now.
