### ISSUE TITLE
Root files no longer exist

### ISSUE THREAD

**Issue by shane-breeze** [cms-l1t-offline/cms-l1t-analysis#64]
The root-files in [1] no longer exists and cause a build error

[1] = https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/Makefile#L40-L47

**Comment by benkrikler** [comment]
I'm surprised by this! I'd have thought our unit tests etc would be failing due to  this, we'll have to double check things!  You should be able to proceed by copying out the actual download of the files from the makefile

**Comment by kreczko** [comment]
@benkrikler The unit tests only run the tests which do not require the data.
We will need to restructure the Makefile to make the file download optional or smarter.

**Comment by kreczko** [comment]
The file paths have been updated several times since, most recently in #123.
