### ISSUE TITLE
Weekly monitoring confiuration

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#66]
In order to help with the routine monitoring we need to create a config that can be run with `cmsl1t`.

Plots required:
- [x] HTT efficiencies
- [x] MHT efficiencies
- [x] MET efficiencies (with HF)
- [x] MET efficiencies (no HF)

2D online vs offline plots for
- [x] MET
- [x] MHT
- [x] MET &phi;
- [x] MET &phi;

Some of this is implemented in #65 but need to be checked and then migrated to the new plotting implementation.

**Comment by benkrikler** [comment]
With issue #77 merged in, we believe we now have the above plots all implemented and a standard weekly-checks config that can be used.  This is probably ready to be closed, unless we want to wait until we merge `weekly-checks` into `master`?

**Comment by kreczko** [comment]
It is fine, closing it now. We should probably merge today and make a new release.
