### ISSUE TITLE
Dirty Batch script on DICE: looking for run_script.sh in submit dir, not batch dir.

### ISSUE THREAD

**Issue by professor-calculus** [cms-l1t-offline/cms-l1t-analysis#83]
I've been playing around trying to get the dirty batch mode running on DICE, but it seems the jobs are all getting held because each job is waiting for <submit_dir>/run_script.sh when the correct path would be <batch_dir>/run_script.sh.

Fixed by changing run_script_name to run_script in Line 44 of cmsl1t_dirty_batch

**Comment by professor-calculus** [comment]
Actually, this would cause the job to fail/be held if <batch_dir> is on /storage or anywhere the worker node cannot read from...

**Comment by benkrikler** [comment]
How does this issue relate to #84?  They seem very similar to me

**Comment by kreczko** [comment]
Dirty batch should be no longer in use
