### ISSUE TITLE
Error reporting when importing a broken analyzer is lousy.

### ISSUE THREAD

**Issue by benkrikler** [cms-l1t-offline/cms-l1t-analysis#88]
#### Description
When we try to obtain an analzyer requested via the config file, we use the `utils.module.exists()` method to check that the analyzer is valid.  However, we check this by trying to import the named module.  If this fails, we simply return `False` and then report the error as the analyzer not being found.  However, many times when developing this is not the correct source of the problem, if, for example, the code in the module is broken and raises an ImportError.  It would be useful to pass this import error through to the user to help them debug their analyzer directly.

Key code relating to this problem:
* https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/cmsl1t/utils/module.py#L9-L24
* https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/cmsl1t/config.py#L171

**Comment by kreczko** [comment]
Yes, @bundocka would have had an easier time if we had this in.
I recommend we change
```python
def exists(module_name):
    try:
        import_module(module_name)
    except ImportError:
        if '.' not in module_name:
            return False
        # check if it is a member of a module instead
        tokens = module_name.split('.')
        module_name = '.'.join(tokens[:-1])
        try:
            m = import_module(module_name)
        except ImportError:
            return False
        return hasattr(m, tokens[-1])
    else:
        return True
```
to 
```python
def exists(module_name):
    try:
        import_module(module_name)
    except ImportError, e1:
        logger.debug('Error importing a module: {}'.format(e1))
        if '.' not in module_name:
            return False
        # check if it is a member of a module instead
        tokens = module_name.split('.')
        module_name = '.'.join(tokens[:-1])
        try:
            m = import_module(module_name)
        except ImportError, e2:
            logger.debug('Error importing a module: {}'.format(e2))
            return False
        return hasattr(m, tokens[-1])
    else:
        return True
```
possibly with module name, etc.
