### ISSUE TITLE
Offline MET Analyser tries to access Phi attribute of HTT (no such thing)

### ISSUE THREAD

**Issue by professor-calculus** [cms-l1t-offline/cms-l1t-analysis#95]
#### Description

The newly-merged PR Offline MET analyser tried to access the Phi attribute of HTT which does not exist. This is since HTT and HTT_Emu are no longer the first 2 elements of sum_types.

These first two are skipped when doing anything involving phi, which of course isn't the only way to do it:
https://github.com/cms-l1t-offline/cms-l1t-analysis/blob/master/cmsl1t/analyzers/offline_met_analyzer.py#L126

I'll put this right and make a PR, just thought it worth mentioning ;-)

**Comment by kreczko** [comment]
This should be fixed in the latest stable version
