### ISSUE TITLE
Failed job resubmission & log files for investigating job failure on batch

### ISSUE THREAD

**Issue by bundocka** [cms-l1t-offline/cms-l1t-analysis#99]
#### Description

Currently no simple way to find out what sub jobs failed and why. Makes the code unusable for large datasets when a lot of sub jobs can fail. Also currently impossible to find out why sub jobs failed on the batch.

**Comment by kreczko** [comment]
From my understanding there are two items for this issue:
 - add `cmsl1t_dirty_batch --status [<batch_directory>]`: report on failed/succeeded jobs quoting reason for failure
 - add `cmsl1t_dirty_batch --resubmit [list of jobs] | --failed` 

This won't cover all problems but should give a simple insight into what is going on.
